# Generated by Django 4.2.24 on 2025-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Document is valid until this date', null=True),
        ),
    ]
