# Generated by Django 4.2.25 on 2025-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_user_date_joined_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('free_trial', 'Free Trial')], max_length=20),
        ),
    ]
