# Generated by Django 5.2.7 on 2025-11-16 16:32

import esign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='initials_image',
            field=models.ImageField(default=1, upload_to=esign.models.sig_image_path),
            preserve_default=False,
        ),
    ]
