# Generated by Django 5.2.7 on 2025-11-26 06:30

import esign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0004_signature_initials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='initials_image',
            field=models.ImageField(blank=True, null=True, upload_to=esign.models.sig_image_path),
        ),
    ]
