# Generated by Django 5.2.7 on 2025-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0005_subscription_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebox',
            name='assigned_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signaturebox',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
