# Generated by Django 5.2.7 on 2025-11-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0005_subscriptionplan_company_companysubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companymembership',
            options={'verbose_name': 'Company Membership', 'verbose_name_plural': 'Company Memberships'},
        ),
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Company Subscription', 'verbose_name_plural': 'Company Subscriptions'},
        ),
        migrations.AddField(
            model_name='marketingsource',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
