# Generated by Django 5.2.7 on 2025-12-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0006_signaturebox_assigned_email_signaturebox_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignflow',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsignflow',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
