# Generated by Django 5.2.7 on 2025-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0007_documentsignflow_is_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
