# Generated by Django 5.2.7 on 2025-12-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0008_document_message_document_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reminder_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
