# Generated by Django 5.2.7 on 2025-12-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0009_document_reminder_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sign_order_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
