# Generated by Django 5.2.7 on 2025-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0010_document_sign_order_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentsignflow',
            name='role',
            field=models.CharField(choices=[('signer', 'Signer'), ('viewer', 'Viewer'), ('cc', 'CC')], default='signer', max_length=20),
        ),
    ]
