# Generated by Django 5.2.7 on 2025-12-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0011_document_is_editable_alter_documentsignflow_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
